server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/habitia
    username: habitia
    password: habitia
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: "a4pg1GSnK9CH7x8jHtTeTDKBuFwhuGOAicr2ZXzSOEBM5ZXjzw4r5BEN5UQEOF6UcEmQONyYqbtzeeKMzOTSyF"
    expirationMs: 86400000  # 24h
  storage:
    provider: ${APP_STORAGE_PROVIDER:local}
    upload-dir: ./uploads
    base-url: http://localhost:8080
  cors:
    allowed-origins: "http://localhost:4200"
  cloudinary:
    cloud-name: ${APP_CLOUDINARY_CLOUD_NAME:}
    api-key: ${APP_CLOUDINARY_API_KEY:}
    api-secret: ${APP_CLOUDINARY_API_SECRET:}

  